from __future__ import annotations
from typing import Iterable, Generic, TypeVar

T = TypeVar("T")
ComposeResult = Iterable[object]

class App(Generic[T]):
    BINDINGS: object
    CSS: str
    focused: object | None

    def __init__(self) -> None: ...
    def compose(self) -> ComposeResult: ...
    def on_mount(self) -> None: ...
    def set_focus(self, widget: object) -> None: ...
    def exit(self, result: T | None = None) -> None: ...
    def run(self) -> T | None: ...
