from __future__ import annotations
from pathlib import Path
import textwrap

from .demo_init_common import write_if_missing


def init_demo_toml(root: Path) -> None:
    """
    Create a minimal ducksite.toml for the demo project.

    Layout assumptions:
      - fake_upstream/ contains the raw parquet files
      - static/ will be generated by ducksite build/serve

    The demo file_source is also configured to use a filename-style
    *template* over the underlying Parquet files:

      [[file_sources]]
      name = "demo"
      template_name = "demo_[category]"
      row_filter_template = "category = ?"

    At build time this is expanded into per-category views like:

      demo_A
      demo_B
      demo_C

    where each view reads the same Parquet files but applies a fixed
    predicate based on the discovered DISTINCT `category` values.
    """
    toml_path = root / "ducksite.toml"
    content = (
        textwrap.dedent(
            """
            # ducksite.toml - dummy config for local testing

            [dirs]
            DIR_FAKE = "fake_upstream"

            [[file_sources]]
            # Base demo file-source view over all demo Parquet files.
            # Files from:
            #   ${DIR_FAKE}/demo-*.parquet
            # are mirrored virtually under:
            #   data/demo/demo-*.parquet
            #
            # So the pattern is rooted at data/<name>/...
            name = "demo"
            template_name = "demo_[category]"
            pattern = "data/demo/*.parquet"
            upstream_glob = "${DIR_FAKE}/demo-*.parquet"
            union_mode = "union_all_by_name"
            row_filter_template = "category = ?"
            """
        ).strip()
        + "\n"
    )
    write_if_missing(toml_path, content)
