from __future__ import annotations
from pathlib import Path

import tomllib

from .demo_init_virtual_plugin import CHAIN_PLUGIN_NAME, DEMO_PLUGIN_NAME
from .tuy_toml import add_file_source_entry, render_config_text
from .utils import ensure_dir


def init_demo_toml(root: Path) -> None:
    """
    Create a minimal ducksite.toml for the demo project.

    Layout assumptions:
      - fake_upstream/ contains the raw parquet files
      - static/ will be generated by ducksite build/serve

    The demo file_source is also configured to use a filename-style
    *template* over the underlying Parquet files:

      [[file_sources]]
      name = "demo"
      template_name = "demo_[category]"
      row_filter_template = "category = ?"

    At build time this is expanded into per-category views like:

      demo_A
      demo_B
      demo_C

    where each view reads the same Parquet files but applies a fixed
    predicate based on the discovered DISTINCT `category` values.
    """
    toml_path = root / "ducksite.toml"
    existing = toml_path.read_text(encoding="utf-8") if toml_path.exists() else ""
    parsed = tomllib.loads(existing) if existing.strip() else {}

    dirs = dict(parsed.get("dirs", {}))
    dirs.setdefault("DIR_FORMS", "static/forms")
    dirs.setdefault("DIR_FAKE", "fake_upstream")

    base_text = render_config_text(
        root,
        dirs=dirs,
        file_sources=parsed.get("file_sources", []),
        comments=["ducksite.toml - dummy config for local testing"],
    )

    demo_entry = {
        "name": "demo",
        "template_name": "demo_[category]",
        "pattern": "data/demo/*.parquet",
        "upstream_glob": "${DIR_FAKE}/demo-*.parquet",
        "union_mode": "union_all_by_name",
        "row_filter_template": "category = ?",
    }

    try:
        rendered = add_file_source_entry(
            base_text,
            demo_entry,
            root,
            comments=[
                "ducksite.toml - dummy config for local testing",
                "Base demo file-source view over all demo Parquet files.",
                "Files from ${DIR_FAKE}/demo-*.parquet are mirrored under data/demo/demo-*.parquet.",
            ],
        )
    except ValueError as exc:
        if "already exists" in str(exc):
            print(
                f"[ducksite:demo] {toml_path} already contains demo file source, skipping insert."
            )
            rendered = base_text
        else:
            raise

    plugin_entry = {
        "name": DEMO_PLUGIN_NAME,
        "pattern": f"data/{DEMO_PLUGIN_NAME}/*.parquet",
        "plugin": f"plugins/{DEMO_PLUGIN_NAME}.py",
        "template_name": "demo_plugin_[category]",
        "row_filter_template": "category = ?",
    }

    try:
        rendered = add_file_source_entry(
            rendered,
            plugin_entry,
            root,
            comments=[
                "ducksite.toml - dummy config for local testing",
                "Virtual plugin example that mirrors demo-A/B/C through a plugin manifest.",
            ],
        )
    except ValueError:
        print(f"[ducksite:demo] {toml_path} already contains plugin file source, skipping.")

    chain_entry = {
        "name": CHAIN_PLUGIN_NAME,
        "pattern": f"data/{CHAIN_PLUGIN_NAME}/**/*.parquet",
        "plugin": f"plugins/{CHAIN_PLUGIN_NAME}.py",
    }

    try:
        rendered = add_file_source_entry(
            rendered,
            chain_entry,
            root,
            comments=[
                "ducksite.toml - dummy config for local testing",
                "Chained plugin example that reuses the demo file list and model views.",
            ],
        )
    except ValueError:
        print(f"[ducksite:demo] {toml_path} already contains chained plugin entry, skipping.")

    hierarchy_entry = {
        "name": "demo_hierarchy",
        "template_name": "demo_hierarchy_[category]",
        "row_filter_template": "category = ?",
        "hierarchy": [
            {"pattern": "data/demo_hierarchy/day/*.parquet", "row_filter": "period = 'day'"},
            {"pattern": "data/demo_hierarchy/month/*.parquet", "row_filter": "period = 'month'"},
            {"pattern": "data/demo_hierarchy/year/*.parquet", "row_filter": "period = 'year'"},
        ],
        "upstream_glob": "${DIR_FAKE}/demo_hierarchy/**/*.parquet",
    }

    try:
        rendered = add_file_source_entry(
            rendered,
            hierarchy_entry,
            root,
            comments=[
                "ducksite.toml - dummy config for local testing",
                "Hierarchy demo combining day/month/year rollups into one source.",
            ],
        )
    except ValueError:
        print(
            f"[ducksite:demo] {toml_path} already contains hierarchy file source, skipping."
        )

    hierarchy_window_entry = {
        "name": "demo_hierarchy_window",
        "template_name": "demo_hierarchy_window_[concat(region, '_', strftime(max_day, '%Y-%m-%d'))]",
        "row_filter": "active = true",
        "row_filter_template": "concat(region, '_', strftime(max_day, '%Y-%m-%d')) = ?",
        "template_values": ["na_2024-12-05"],
        "hierarchy_before": [
            {"pattern": "data/demo_hierarchy_window/day_start/*.parquet", "row_filter": "period = 'edge-start'"}
        ],
        "hierarchy": [
            {"pattern": "data/demo_hierarchy_window/day/*.parquet", "row_filter": "period = 'day'"},
            {"pattern": "data/demo_hierarchy_window/month/*.parquet", "row_filter": "period = 'month'"},
            {"pattern": "data/demo_hierarchy_window/year/*.parquet", "row_filter": "period = 'year'"},
        ],
        "hierarchy_after": [
            {"pattern": "data/demo_hierarchy_window/day_end/*.parquet", "row_filter": "period = 'edge-end'"}
        ],
        "upstream_glob": "${DIR_FAKE}/demo_hierarchy_window/**/*.parquet",
    }

    try:
        rendered = add_file_source_entry(
            rendered,
            hierarchy_window_entry,
            root,
            comments=[
                "ducksite.toml - dummy config for local testing",
                "Hierarchy demo with before/after windows, templated by region and date.",
            ],
        )
    except ValueError:
        print(
            f"[ducksite:demo] {toml_path} already contains hierarchy window file source, skipping."
        )

    ensure_dir(toml_path.parent)
    toml_path.write_text(rendered, encoding="utf-8")
    print(f"[ducksite:demo] wrote {toml_path}")
